<?php

class AiPromptWriter
{
    public function write(AiContext $context, $file)
    {
        $out = array();

        $out[] = '============================================================';
        $out[] = 'OPENMAGE AI DEVELOPMENT PROMPT';
        $out[] = '============================================================';
        $out[] = '';
        $out[] = 'You are assisting with a Magento 1.x / OpenMage project.';
        $out[] = '';
        $out[] = 'This prompt is intended to be used with these generated profiler files:';
        $out[] = '';
        $out[] = '1. ai-project-context.txt';
        $out[] = '   A compact architectural briefing and risk map.';
        $out[] = '';
        $out[] = '2. ai-project-profile.txt';
        $out[] = '   The full authoritative profiler report.';
        $out[] = '';
        $out[] = 'The context file is not a complete inventory. It is a high-signal summary';
        $out[] = 'designed to point you towards the relevant sections of the full profile.';
        $out[] = '';
        $out[] = 'The full profile is the authoritative technical inventory generated from';
        $out[] = 'the Magento/OpenMage installation.';
        $out[] = '';
        $out[] = '------------------------------------------------------------';
        $out[] = 'FORENSIC WORKFLOW';
        $out[] = '------------------------------------------------------------';
        $out[] = '';
        $out[] = 'Before answering any development question:';
        $out[] = '';
        $out[] = '1. Read ai-project-context.txt first.';
        $out[] = '2. Use it as the orientation and risk map.';
        $out[] = '3. Then inspect the relevant sections of ai-project-profile.txt.';
        $out[] = '4. Do not rely only on the compact context file.';
        $out[] = '5. Do not infer that something is absent merely because it is not shown';
        $out[] = '   in the compact context.';
        $out[] = '6. If the context highlights conflicts, missing files, custom classes,';
        $out[] = '   high-impact observers, cron jobs, routes, controllers, rewrites,';
        $out[] = '   layout files, themes or EAV data, inspect the matching full-profile';
        $out[] = '   section before recommending changes.';
        $out[] = '';
        $out[] = 'Treat the generated profiler output as authoritative runtime/configuration';
        $out[] = 'behaviour for the Magento/OpenMage installation.';
        $out[] = '';
        $out[] = 'If source code is also uploaded, treat the source code as authoritative';
        $out[] = 'implementation and compare it against the generated profiler output before';
        $out[] = 'suggesting code changes.';
        $out[] = '';
        $out[] = 'If the source code and generated profiler output appear to disagree,';
        $out[] = 'investigate why before proposing changes.';
        $out[] = '';
        $out[] = '------------------------------------------------------------';
        $out[] = 'DEVELOPMENT RULES';
        $out[] = '------------------------------------------------------------';
        $out[] = '';
        $out[] = '- Assume Magento 1.x / OpenMage, not Magento 2.';
        $out[] = '- Assume PHP 7.4 compatibility unless the project profile says otherwise.';
        $out[] = '- Prefer backwards-compatible changes.';
        $out[] = '- Prefer modifying existing custom modules over creating new modules.';
        $out[] = '- Never suggest editing Magento core files directly.';
        $out[] = '- Always include exact file paths.';
        $out[] = '- Always provide complete code where practical.';
        $out[] = '- Explain architectural decisions briefly.';
        $out[] = '- Be careful with rewrites, observers, layout XML, routers, controllers,';
        $out[] = '  cron jobs, EAV attributes, setup resources and theme fallback.';
        $out[] = '- Treat the installation as production unless told otherwise.';
        $out[] = '';
        $out[] = '------------------------------------------------------------';
        $out[] = 'WHEN ADVISING ON SPECIFIC AREAS';
        $out[] = '------------------------------------------------------------';
        $out[] = '';
        $out[] = 'Theme/frontend work:';
        $out[] = '- Check Theme Architecture, Theme Resolution, Theme Hierarchy, Theme';
        $out[] = '  Fallback Map, XML Merge Analysis, Layout Architecture, Layout Graph';
        $out[] = '  and Template Architecture before advising on templates, layout XML,';
        $out[] = '  skin files or CSS.';
        $out[] = '';
        $out[] = 'Rewrite work:';
        $out[] = '- Check Rewrite Architecture, Rewrite Map and Rewrite Chains before';
        $out[] = '  advising on model, block or helper overrides.';
        $out[] = '';
        $out[] = 'Observer work:';
        $out[] = '- Check Observer Architecture, Event Dispatch Architecture and highlighted';
        $out[] = '  observer sections before advising on event-driven behaviour.';
        $out[] = '';
        $out[] = 'Cron/integration work:';
        $out[] = '- Check Cron Architecture and highlighted cron sections before advising';
        $out[] = '  on imports, exports, queues, email, indexing or integrations.';
        $out[] = '';
        $out[] = 'Routing/controller work:';
        $out[] = '- Check Router Architecture, Controller Architecture and Route Controller';
        $out[] = '  Map before advising on frontName, admin routes, controller paths or AJAX endpoints.';
        $out[] = '';
        $out[] = 'Product/category/customer attribute work:';
        $out[] = '- Check EAV Architecture and the full EAV collector output before advising';
        $out[] = '  on attributes, attribute sets, backend models, source models or setup scripts.';
        $out[] = '';
        $out[] = 'Performance work:';
        $out[] = '- Check Cache Architecture, Index Architecture, Cron Architecture, Rewrite';
        $out[] = '  Architecture, Observer Architecture and Layout Architecture before advising.';
        $out[] = '';
        $out[] = 'Database/setup work:';
        $out[] = '- Check Database Architecture, Database Schema and module setup resource';
        $out[] = '  information before advising on setup scripts, resource versions or table-level changes.';
        $out[] = '';
        $out[] = 'Large/custom code work:';
        $out[] = '- Check Code Complexity, Module Dependency Graph, Dead Code Indicators,';
        $out[] = '  Code Relationship Index, AI Index, Search Tags and Risk Report before';
        $out[] = '  editing large custom helpers, models, controllers or legacy modules.';
        $out[] = '';
        $out[] = '------------------------------------------------------------';
        $out[] = 'RECOMMENDED USAGE';
        $out[] = '------------------------------------------------------------';
        $out[] = '';
        $out[] = 'Upload these files together:';
        $out[] = '';
        $out[] = '- ai-chatgpt-prompt.txt';
        $out[] = '- ai-project-context.txt';
        $out[] = '- ai-project-profile.txt';
        $out[] = '';
        $out[] = 'Then ask the actual development question.';
        $out[] = '';
        $out[] = 'Suggested first message:';
        $out[] = '';
        $out[] = '"Use the attached OpenMage AI Profiler prompt, compact context and full';
        $out[] = 'profile report as the authoritative technical context for this Magento';
        $out[] = '1.x/OpenMage project. Before suggesting changes, read the compact context';
        $out[] = 'first, then inspect the relevant full-profile sections. Include exact file';
        $out[] = 'paths and complete code changes where practical."';
        $out[] = '';

        $out[] = '';
        $out[] = 'This prompt intentionally does not include the generated context data.';
        $out[] = 'Use ai-project-context.txt for the compact briefing and ai-project-profile.txt';
        $out[] = 'for the full authoritative report.';
        $out[] = '';

        file_put_contents($file, implode("\n", $out));
    }
}