<?php

class CodexAgentsWriter
{
    public function write(AiContext $context, $file, $aiDirectory, $localInstructionsFile = null)
    {
        $aiDirectory = rtrim(str_replace('\\', '/', $aiDirectory), '/');

        if ($aiDirectory === '') {
            $aiDirectory = '.';
        }

        $promptPath = $aiDirectory . '/ai-chatgpt-prompt.txt';
        $contextPath = $aiDirectory . '/ai-project-context.txt';
        $profilePath = $aiDirectory . '/ai-project-profile.txt';
        $jsonPath = $aiDirectory . '/ai-project-profile.json';
        $markdownPath = $aiDirectory . '/ai-project-profile.md';

        $out = array();

        $out[] = '# OpenMage / Magento 1.x Project Instructions';
        $out[] = '';
        $out[] = 'This is a Magento 1.x / OpenMage project, not Magento 2.';
        $out[] = '';
        $out[] = 'The files under `' . $aiDirectory . '` were generated by OpenMage AI Profiler and describe the live Magento/OpenMage runtime, configuration and architecture.';
        $out[] = '';
        $out[] = '## Before making development changes';
        $out[] = '';
        $out[] = '1. Read `' . $promptPath . '`.';
        $out[] = '2. Read `' . $contextPath . '` for orientation.';
        $out[] = '3. Inspect relevant sections of `' . $profilePath . '`.';
        $out[] = '4. Use `' . $jsonPath . '` when structured data is easier to query than text.';
        $out[] = '5. Use `' . $markdownPath . '` when working in Codex, GitHub, Cursor, VS Code or pull requests.';
        $out[] = '6. Then inspect the actual source files being changed.';
        $out[] = '7. Treat the source code as authoritative implementation.';
        $out[] = '8. Treat the profiler files as authoritative runtime/configuration context.';
        $out[] = '9. If source code and profiler output disagree, investigate before changing code.';
        $out[] = '';
        $out[] = '## Development rules';
        $out[] = '';
        $out[] = '- Assume PHP 7.4 compatibility unless the profiler output proves otherwise.';
        $out[] = '- Do not edit Magento core files directly.';
        $out[] = '- Prefer modifying existing custom modules over creating new modules.';
        $out[] = '- Preserve Magento 1.x/OpenMage conventions.';
        $out[] = '- Keep changes small, reviewable and backwards-compatible.';
        $out[] = '- Include exact file paths in summaries.';
        $out[] = '- For PHP changes, run `php -l` on changed files where possible.';
        $out[] = '- For XML changes, validate XML syntax where possible.';
        $out[] = '';
        $out[] = '## Magento/OpenMage caution areas';
        $out[] = '';
        $out[] = '- Rewrites and rewrite chains.';
        $out[] = '- Observers and event dispatches.';
        $out[] = '- Layout XML and merged layout handles.';
        $out[] = '- Theme fallback and template resolution.';
        $out[] = '- Routers, frontNames, controllers and actions.';
        $out[] = '- Cron jobs and integration queues.';
        $out[] = '- EAV attributes, attribute sets, backend models and source models.';
        $out[] = '- Setup resources and database schema changes.';
        $out[] = '- Store-view-specific configuration.';
        $out[] = '';
        $out[] = '## Area-specific guidance';
        $out[] = '';
        $out[] = '### Theme/frontend work';
        $out[] = '';
        $out[] = 'Before editing templates, layout XML, skin files or CSS, check Theme Architecture, Theme Resolution, Theme Hierarchy, Theme Fallback Map, XML Merge Analysis, Layout Architecture, Layout Graph and Template Architecture in the profiler output.';
        $out[] = '';
        $out[] = '### Rewrite work';
        $out[] = '';
        $out[] = 'Before editing model, block or helper overrides, check Rewrite Architecture, Rewrite Map and Rewrite Chains.';
        $out[] = '';
        $out[] = '### Observer work';
        $out[] = '';
        $out[] = 'Before changing event-driven behaviour, check Observer Architecture and Event Dispatch Architecture for the affected event.';
        $out[] = '';
        $out[] = '### Routing/controller work';
        $out[] = '';
        $out[] = 'Before changing frontName, admin routes, controller paths or AJAX endpoints, check Router Architecture, Controller Architecture and Route Controller Map.';
        $out[] = '';
        $out[] = '### Product/category/customer attribute work';
        $out[] = '';
        $out[] = 'Before changing product, category, customer or customer-address attributes, check EAV Architecture and the full EAV collector output.';
        $out[] = '';
        $out[] = '### Cron/integration work';
        $out[] = '';
        $out[] = 'Before changing imports, exports, queues, email, indexing or integrations, check Cron Architecture and relevant module declarations.';
        $out[] = '';
        $out[] = '### Database/setup work';
        $out[] = '';
        $out[] = 'Before changing setup scripts, resource versions or table-level logic, check Database Architecture, Database Schema and module setup resource information.';
        $out[] = '';
        $out[] = '### Large/custom code work';
        $out[] = '';
        $out[] = 'Before editing large custom helpers, models, controllers or legacy modules, check Code Complexity, Module Dependency Graph, Dead Code Indicators, Code Relationship Index, AI Index, Search Tags and Risk Report.';
        $out[] = '';
        $out[] = '## Useful validation commands';
        $out[] = '';
        $out[] = '```bash';
        $out[] = 'git diff --name-only -- "*.php" | xargs -r -n1 php -l';
        $out[] = 'git diff --name-only -- "*.xml" | xargs -r -n1 xmllint --noout';
        $out[] = '```';
        $out[] = '';
        $out[] = '## Expected workflow for Codex';
        $out[] = '';
        $out[] = 'When asked to make a change:';
        $out[] = '';
        $out[] = '1. Use these instructions and the profiler files first.';
        $out[] = '2. Identify relevant rewrites, observers, layout XML, theme fallback, routes, controllers, cron jobs, EAV data and source files.';
        $out[] = '3. Explain findings briefly.';
        $out[] = '4. Make the smallest safe change.';
        $out[] = '5. Summarise changed files and why each change was made.';
        $out[] = '';
        $out[] = 'Do not make Magento 2-style changes in this repository.';
        $out[] = '';
        
        if (
            $localInstructionsFile !== null
            && is_file($localInstructionsFile)
            && is_readable($localInstructionsFile)
        ) {
            $localInstructions = trim((string)file_get_contents($localInstructionsFile));

            if ($localInstructions !== '') {
                $out[] = '';
                $out[] = '---';
                $out[] = '';
                $out[] = '# Project-specific local instructions';
                $out[] = '';
                $out[] = $localInstructions;
                $out[] = '';
            }
        }

        $result = file_put_contents(
            $file,
            implode("\n", $out) . "\n"
        );

        if ($result === false) {
            throw new Exception('Unable to write Codex AGENTS.md file: ' . $file);
        }
    }
}
